### ISSUE TITLE
Mechanism for letting requesters test and debug their own tasks

### ISSUE THREAD

**Issue by neilthemathguy** [crowdresearch/crowdsource-platform#380]
At present preview functionality on the drag-drop shows the task interface mockup. Enhance it to handle Preview and Debug

**Comment by maniksingh92** [comment]
@neilthemathguy What should the Debug feature do?  and any modifications required to the preview feature?

**Comment by dmorina** [comment]
pasting the reply from @mbernst  "in AMT, people have a “requester sandbox” they can push their tasks to. it’s a version of AMT with no workers on it so that you can try out your own task and make sure it works. Especially helpful if you have logic on the back end that’s trying to combine multiple workers’ actions and you need to test it. This can be simulated without a separate sandbox by letting me set a task as one that only I can do. Not high priority, just wanted to mention so that we don’t paint ourselves into a corner later."

**Comment by neilthemathguy** [comment]
Sandbox like functionality is very useful. Here is the MTurk  [sandbox](https://workersandbox.mturk.com/mturk/welcome 
).  I think there are multiple ways to achieve this in our platform, I will add the details here. We can brainstorm around this further. For now I will flag it as a *Need to be Prioritize;* and we can revisit this during the refactoring.
