### ISSUE TITLE
Not able to use postgres in dev environment

### ISSUE THREAD

**Issue by swapagarwal** [crowdresearch/crowdsource-platform#5]
I wasn't able to connect to database using postgres.
However, I could connect to sqlite3 easily by changing local_settings.py from
```python
DATABASES = {
   "default": {
       "ENGINE": "django.db.backends.postgresql_psycopg2",
       "NAME": "crowdsource_dev"
   }
}
```
to 
```python
DATABASES = {
   'default': {
       'ENGINE': 'django.db.backends.sqlite3',
       'NAME': 'crowdresearch.db',
   }
}
```

**Comment by neilthemathguy** [comment]
What error are you getting while connecting?

**Comment by dmorina** [comment]
django.db.utils.ProgrammingError: column django_content_type.name does not exist.

I guess he fails to build the models

**Comment by ksetyadi** [comment]
I have pushed this regarding this issue. Take a look at angular-fixes newer
push. It's because Django 1.7 still have ContentType.Name in real field
while Django 1.8 didn't.

Pull again and run: pip install -r requirements.txt

It will solve your problem.


Regards,
Kristiono Setyadi
http://ksetyadi.com
