### ISSUE TITLE
Full text search

### ISSUE THREAD

**Issue by dmorina** [crowdresearch/crowdsource-platform#80]
Postgres supports full text search and it's really fast, the idea is to integrate that into Django Models, migrations would have to be written to create Database functions, triggers and indexes for the fields we want to search on.

DRI: @dmorina @neilthemathguy @nistala

**Comment by v1p** [comment]
@dmorina @neilthemathguy @nistala : Any thoughts about using 'djorm-ext-pgfulltext' rather than rewriting a major component of the repo? 
 
if we don't have a hard drawn dependency on using Postgres as the only viable & available option, we 'can' look into elasticsearch with haystack. 

I am not sure to what extent we can use external open-source libraries in this project, if you would guide me that if we have certain protocol for this...

**Comment by gkovacs** [comment]
@v1p Yes open-source libraries under most common, permissive open-source licenses (apache, MIT, BSD, LGPL, etc) should be ok. Just not GPL ones (since using GPL libraries would force us to use the GPL license).

**Comment by dmorina** [comment]
@v1p yes we have explored this option, it's a private license, anyways writing the full text is not that difficult and we want to use all the features of postgres fulltext like misspelling of search query and stuff like that

**Comment by v1p** [comment]
@dmorina @gkovacs Thanks a ton for clarifying :)

**Comment by v1p** [comment]
Is this still open ? If yes then I'll start working on in tomorrow. Thanks!
