### ISSUE TITLE
Applying academic discount doesn't update the default deposit amount

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/crowdsource-platform#850]
If I don't edit the default deposit amount, it stays at the old number after the AJAX realizes that it should be less. In this image, the deposit was $4 even, but then it realized there was a discount, and updated all numbers except the textbox. I suppose that if the user hasn't updated the number and the textbox isn't focused, we could update that amount automatically?

<img width="554" alt="screen shot 2017-06-09 at 9 14 24 pm" src="https://user-images.githubusercontent.com/249285/26999897-15bbe5f0-4d59-11e7-881d-ac0e92e62ec2.png">

**Comment by shirishgoyal** [comment]
Ideally we should collect the same amount from them that they are filling and then give them virtual credits to run double the number of tasks. It should never increase their displayed $ value in credits. Otherwise, if they ask for full refund, that will mean we legally have to pay them more than they are entitled for.

**Comment by dmorina** [comment]
umm im confused, why would the amount change? the "Your credit card will be charged" value is?

**Comment by dmorina** [comment]
if they ask for a refund we only have to refund their credit card charges .

**Comment by shirishgoyal** [comment]
But what is the displayed value in their credits? As per what Michael is saying above, it appears like it will show $4 even though they got charged $2.38

**Comment by dmorina** [comment]
the 2.38 is all that matters, sure they will be given 4 daemo dollars :D

**Comment by dmorina** [comment]
i think what's missing is a refund policy on the page otherwise it's fine .. but we dont refund anyway :D

**Comment by mbernst** [comment]
Sorry, I wasn't clear. I wanted to launch $4 in tasks. So I went to deposit. Originally the page said I had to deposit $4. Then it realized I got the academic discount via AJAX/Angular, and updated most of the page to reduce my cost. Except it left the amount that I was depositing the same. If I now need less in order to cover my costs, shouldn't it reduce that deposit amount?

**Comment by dmorina** [comment]
ah just the default you mean, sure i guess (?) they can change it by themselves (?)

**Comment by mbernst** [comment]
Yeah, I was mainly suggesting that the default # change if/when we realize that their costs have shifted.

**Comment by dmorina** [comment]
@mbernst sorry, I'm still struggling with this one ... and i think because it's correct as it is and reason is this:
half off works like this: there's an amount of funds X required to post a project (or the requester wants to deposit a certain amount), now they pay half we pay the other half.

My point is that X doesn't change, it's not that we need less money for this project, it's just that you'll end up being charged half of that amount. And the "deposit amount" specifies how much Daemo credits ($) they'd like to purchase, if we change that to half they will end up being charged 1/4 of the required (original) amount which is not what we want.

**Comment by mbernst** [comment]
Ah, I see. OK, let's close it.
